# Generated by Django 4.1.7 on 2023-08-07 15:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("app01", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userinfo",
            name="account",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="账户余额"
            ),
        ),
        migrations.AddField(
            model_name="userinfo",
            name="create_time",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="日期"
            ),
        ),
        migrations.AddField(
            model_name="userinfo",
            name="depart_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="app01.department",
            ),
        ),
        migrations.AddField(
            model_name="userinfo",
            name="gender",
            field=models.SmallIntegerField(
                choices=[(1, "男"), (2, "女")], default=1, verbose_name="性别"
            ),
        ),
        migrations.AlterField(
            model_name="department",
            name="title",
            field=models.CharField(max_length=32, verbose_name="部门"),
        ),
        migrations.AlterField(
            model_name="userinfo",
            name="age",
            field=models.IntegerField(default=0, verbose_name="年龄"),
        ),
        migrations.AlterField(
            model_name="userinfo",
            name="name",
            field=models.CharField(max_length=32, verbose_name="姓名"),
        ),
        migrations.AlterField(
            model_name="userinfo",
            name="password",
            field=models.CharField(max_length=64, verbose_name="密码"),
        ),
    ]
