# Generated by Django 4.1.7 on 2023-08-21 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("app01", "0002_userinfo_account_userinfo_create_time_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userinfo",
            name="depart_id",
        ),
        migrations.AddField(
            model_name="userinfo",
            name="depart",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="app01.department",
            ),
        ),
    ]
